Squashed commit of the following:
commit 60b6bc595f20b29f4869d3236ce1aa91a490ef6b
Author: Andre McGrail <andrem@unity3d.com>
Date:   Mon Nov 9 17:32:00 2020 +0100

    Update README.md

commit 87dc01efaab4c7911d5af79355707930b4b4b00b
Author: Andre McGrail <andrem@unity3d.com>
Date:   Mon Nov 9 17:27:13 2020 +0100

    Update README.md

commit 35e7524eded7d0d639332bfb4a17547481aaa91d
Author: Andre McGrail <andrem@unity3d.com>
Date:   Mon Nov 9 17:26:53 2020 +0100

    Update README.md

commit 46718e5dc3772f43ef0b159d75e96588514a68c5
Author: Andre McGrail <andrem@unity3d.com>
Date:   Wed Nov 4 16:29:21 2020 +0100

    Feature/benchmark (#126)

    * Benchmark base

    * fix shader library compile regression

    * Fix FBX errors

    * automated run from editor WIP

    * more work, cleanup of UI prefabs

    * static angle scene

    First pass

    * Squashed commit of the following:

    commit fdd4ba7dc6a6fabd561ea186b4453735ac9103eb
    Author: Andre McGrail <andrem@unity3d.com>
    Date:   Fri Sep 4 13:54:37 2020 +0200

        Changed Lod Lightmaps to run only in editor and only when needed (#118)

    * Fix benchmark build errors

    * Fixed texture compression warning on build

    * Fixed profiling scope errors

    * removed terrain group missing script

    * Fixed flythrough playing automatically, also added camera prefab to benchmark scenes for easy future updating

    * cleanup

    * enable playmode tests in project (#120)

    * enable playmode tests in project

    * upgrade input system

    * Revamp postprocessing default volume

    * Assorted cleanup and fixes

    * Fixed volume quality levels

    * Potential camera and volume fixes

    * fixed simultaneous loading of volumes from happening

    * Enable test script defines and force no batch mode during test runs (#122)

    * enable test script defines and force no batch mode during test runs

    * disable Cinemachine as it's throwing this error:

    ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
    Parameter name: index
    System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <9577ac7a62ef43179789031239ba8798>:0)
    System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <9577ac7a62ef43179789031239ba8798>:0)
    Cinemachine.CinemachineBrain.UpdateFrame0 (System.Single deltaTime) (at D:/BoatAttack2/Library/PackageCache/com.unity.cinemachine@2.6.3/Runtime/Behaviours/CinemachineBrain.cs:675)
    Cinemachine.CinemachineBrain.ManualUpdate () (at D:/BoatAttack2/Library/PackageCache/com.unity.cinemachine@2.6.3/Runtime/Behaviours/CinemachineBrain.cs:336)
    Cinemachine.CinemachineBrain.OnSceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at D:/BoatAttack2/Library/PackageCache/com.unity.cinemachine@2.6.3/Runtime/Behaviours/CinemachineBrain.cs:235)
    UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <9584de3444b542abbb1ad4bb43a7137f>:0)

    * add link.xml so we don't strip our test assemblies. (#124)

    * Squashed commit of the following:

    commit bfd9f9a1545cb013f6b3cde03eb8996abd2e913f
    Author: Andre McGrail <andrem@unity3d.com>
    Date:   Fri Oct 30 15:41:54 2020 +0100

        Last commit, minor cleanup and setting up benchmark to be able to be run without stats

    commit b927891a1a6ee3d5920efcd50802991251a1d2e0
    Author: Andre McGrail <andrem@unity3d.com>
    Date:   Tue Oct 27 10:54:08 2020 +0100

        disabled benchmark button in main menu

    commit 887084f4c78a255bf7cbc31fc15510052d328db8
    Author: Andre McGrail <andrem@unity3d.com>
    Date:   Tue Oct 27 10:45:11 2020 +0100

        Worked on ingame UI, worked on perf stats working standalone

    commit 4f317fe255e9f773fb4f2f591b73fc4dc9a587de
    Author: André McGrail <andrem@unity3d.com>
    Date:   Thu Oct 22 17:28:16 2020 +0200

        More work on the benchmark tooling, got single scene editor and player runs working

    commit 6a55dfdfa06c933bed7c038c56df2c4405fa0421
    Author: André McGrail <andrem@unity3d.com>
    Date:   Thu Oct 15 16:30:30 2020 +0200

        continued work on benchmark window

    commit 7a3e19ad34d431765a3a4c3d68a15e007033ce06
    Author: André McGrail <andrem@unity3d.com>
    Date:   Thu Oct 15 16:27:48 2020 +0200

        benchmark window working, cleaned up defaultvolume

    commit 79fd0640462a06ca4d3fe4d26dd8cdbf0d42bb7a
    Author: Andre McGrail <andrem@unity3d.com>
    Date:   Mon Oct 12 19:23:11 2020 +0200

        Work on graph rendering, reordered benchmark data

    commit 3007d3f307a9b139e5215e337c185196f057d96a
    Author: André McGrail <andrem@unity3d.com>
    Date:   Thu Oct 8 18:45:19 2020 +0200

        Init push

    * Update to URP public 10.1.0

    - fix loading issues with addressables if scene exists in the build list

    Co-authored-by: Sean Stolberg <33635214+seanstolberg-unity@users.noreply.github.com>

commit fdd4ba7dc6a6fabd561ea186b4453735ac9103eb
Author: Andre McGrail <andrem@unity3d.com>
Date:   Fri Sep 4 13:54:37 2020 +0200

    Changed Lod Lightmaps to run only in editor and only when needed (#118)

commit 98741bf1fa550d8bba0d7ae28cdaea7fa49b6f5b
Author: Andre McGrail <andrem@unity3d.com>
Date:   Mon Aug 3 17:21:35 2020 +0200

    Fixed issue with URP 10.x.x conflicting with SurfaceData struct